create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.profiles enable row level security;
grant select,insert,update on public.profiles to authenticated;
create table if not exists public.roles(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,permissions jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),unique(organization_id,name));
alter table public.roles enable row level security;
grant select,insert,update,delete on public.roles to authenticated;
alter table public.organization_members add column if not exists role_id uuid references public.roles(id) on delete set null;
grant select on public.organizations to authenticated;
grant select,insert,update,delete on public.organization_members to authenticated;
create policy profiles_self_select on public.profiles for select to authenticated using(id=(select auth.uid()));
create policy profiles_self_insert on public.profiles for insert to authenticated with check(id=(select auth.uid()));
create policy profiles_self_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy roles_tenant_select on public.roles for select to authenticated using(private.is_org_member(organization_id));
create policy roles_tenant_write on public.roles for all to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=roles.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin'))) with check(exists(select 1 from public.organization_members m where m.organization_id=roles.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy org_members_admin_insert on public.organization_members for insert to authenticated with check(user_id=(select auth.uid()) or exists(select 1 from public.organization_members m where m.organization_id=organization_members.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy org_members_admin_update on public.organization_members for update to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=organization_members.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin'))) with check(exists(select 1 from public.organization_members m where m.organization_id=organization_members.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create policy org_members_admin_delete on public.organization_members for delete to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=organization_members.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin')));
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing; return new; end;$$;
revoke all on function private.handle_new_user() from public,anon,authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
create index if not exists roles_organization_id_idx on public.roles(organization_id);
create index if not exists organization_members_role_id_idx on public.organization_members(role_id);
